@echo off
echo Starting backend server...
start powershell -NoExit -Command "cd backend; .\venv\Scripts\python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
echo Starting frontend server...
start powershell -NoExit -Command "cd frontend; npm run dev"
echo Opening web page...
ping 127.0.0.1 -n 4 > nul
start http://localhost:3000
